#!/bin/bash
# cleanup v0

# removes all test logs

if [ "$1" == "-f" ]; then
	grep "Debug.testLog" -r --with-filename -n ./src/*.java --color=always
else
	sed "/Debug.testLog/d" -i $(find -name "*.java")
fi
