#!/bin/bash

req 'xdotool'
req 'java-run'

sleepiness=0.1

java-run &
sleep 0.7
xdotool keydown Ctrl;
xdotool keydown Shift;
xdotool keydown Alt;
xdotool keydown Down;
xdotool keyup Down;
xdotool keyup Alt;
xdotool keyup Shift;
xdotool keyup Ctrl;

xdotool mousemove 54 33 # fullscreen
sleep 0.3
xdotool click 1
sleep $sleepiness
xdotool mousemove 380 300 # login
xdotool click 1
sleep $sleepiness
xdotool mousemove 370 140 # create server-menu
xdotool click 1
sleep $sleepiness
xdotool mousemove 350 380 # create server
xdotool click 1
sleep $sleepiness
xdotool mousemove 1200 290 # choose map
xdotool click 1
sleep $sleepiness
xdotool mousemove 1200 660 # next phase
xdotool click 1
sleep $sleepiness
xdotool mousemove 170 230 # choose avatar
xdotool click 1
sleep $sleepiness
xdotool mousemove 262 180 # archer
xdotool click 1
sleep $sleepiness
xdotool mousemove 313 718 # ok
xdotool click 1
sleep $sleepiness
xdotool mousemove 1200 660 # next phase
xdotool click 1
sleep $sleepiness
xdotool mousemove 171 258 # choose skills
xdotool click 1
sleep $sleepiness
xdotool mousemove 262 180 # arrow
xdotool click 1
xdotool click 1
xdotool click 1
xdotool click 1
sleep $sleepiness
xdotool mousemove 313 718 # ok
xdotool click 1
sleep $sleepiness
xdotool mousemove 1200 660 # next phase
xdotool click 1
sleep $sleepiness
xdotool mousemove 195 229 # choose items
xdotool click 1
sleep $sleepiness
xdotool mousemove 262 180 # health ring
xdotool click 1
xdotool click 1
xdotool click 1
sleep $sleepiness
xdotool mousemove 313 718 # ok
xdotool click 1
sleep $sleepiness
xdotool mousemove 1200 660 # next phase
xdotool click 1
sleep $sleepiness
